### ISSUE TITLE
TypeError: Cannot read property 'returnAllParams' of undefined

### ISSUE THREAD

**Issue by sapsaldog** [JohnKimDev/sails-hook-req-validate#1]
I found an error.

TypeError: Cannot read property 'returnAllParams' of undefined
    at returnData (/Users/sapsaldog/Project/herald/node_modules/sails-hook-req-validate/lib/index.js:67:17)
    at Object.module.exports (/Users/sapsaldog/Project/herald/node_modules/sails-hook-req-validate/lib/index.js:231:10)
    at Object.generate [as bill/generate] (/Users/sapsaldog/Project/herald/api/controllers/BillController.js:14:20)
    at /Users/sapsaldog/Project/herald/node_modules/sails/lib/router/bind.js:236:53
    at routeTargetFnWrapper (/Users/sapsaldog/Project/herald/node_modules/sails/lib/router/bind.js:392:9)
    at Layer.handle [as handle_request] (/Users/sapsaldog/Project/herald/node_modules/express/lib/router/layer.js:95:5)

this can be fixed if changes some code in 'config/globals.js'

  _: require('lodash'), //require('@sailshq/lodash'),

I already fixed that, but I think it could be helpful to improve your repository

**Comment by akkivarma** [comment]
I am also getting the similar type of error

TypeError: Cannot read property 'inputErrorMessage' of undefined
    at checkValidation (/Users/akshayvarma/WebstormProjects/chattr/backend/node_modules/sails-hook-req-validate/lib/validator.js:22:29)
    at Object.stringValidationCheck (/Users/akshayvarma/WebstormProjects/chattr/backend/node_modules/sails-hook-req-validate/lib/validator.js:52:14)
    at module.exports (/Users/akshayvarma/WebstormProjects/chattr/backend/node_modules/sails-hook-req-validate/lib/helper.js:17:22)
    at /Users/akshayvarma/WebstormProjects/chattr/backend/node_modules/sails-hook-req-validate/lib/index.js:129:26
    at /Users/akshayvarma/WebstormProjects/chattr/backend/node_modules/lodash/index.js:3073:15
    at baseForOwn (/Users/akshayvarma/WebstormProjects/chattr/backend/node_modules/lodash/index.js:2046:14)
    at /Users/akshayvarma/WebstormProjects/chattr/backend/node_modules/lodash/index.js:3043:18
    at Function.<anonymous> (/Users/akshayvarma/WebstormProjects/chattr/backend/node_modules/lodash/index.js:3346:13)
    at Object.module.exports (/Users/akshayvarma/WebstormProjects/chattr/backend/node_modules/sails-hook-req-validate/lib/index.js:113:7)

**Comment by toksdotdev** [comment]
Any update on this?

**Comment by JohnKimDev** [comment]
fixed in v2.7..1
